spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.56.101:3306/dbsell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

env:
  test

girl:
  name: yien7
  age: 28
